### ISSUE TITLE
Announce feature

### ISSUE THREAD

**Issue by Luffty** [Limmek/Shitlist#5] opened 2023-01-19 04:09 UTC
Hi
Shitlist has worked like a charm since my last writing.

However, there is one feature i think would be great.
Raid announcement :)

A way to let the entire raid know about a certain person, instead of it being limited to just 1 group within the raid, as that is all the party announce can do at this point

**Comment by Limmek** [comment] 2023-01-26 11:11
Hello,
I'm currently working on a complete rewrite of the addon (Shitlist 2.0) using [ace3 ](https://[www.wowace.com](https://www.wowace.com/projects/ace3/pages/getting-started)/projects/ace3/pages/getting-started) and some other libs.
This feature is already planed to be implemented.
_Announcements -> Guild, Party, Instance & Raid._

Some other features is
* **[DONE]** Minimap Icon
* **[DONE]** Localization 
* **[DONE]** Profiles (global or character specific)
* **[DONE]** Ability to display only the reason and/or description or both.
* **[DONE]** Set custom colors on reasons and player description.
* **[DONE]** Improved announcement send player note to chat (Guild, Party, Raid, Instance), enable/disable send to chat on a specifik player.
* **[DONE]** Improved sound, ability to enable/disable sound alert for specifik reason.
* **[TODO]** Import/Export listed players

**Comment by Luffty** [comment] 2023-03-13 08:54
How's the work coming along? :)
Figured i'd give it a lil time before asking, as RL comes before anything else

**Comment by Limmek** [comment] 2023-03-15 12:36
Sorry for the delay yeah you are right i have prioritized some RL stuff.
I will upload the 2.0 branch tonight and you are welcome to test it out before i merge it in to the main.
Since i want to be sure the old tables with listed player and reason data will not break when releasing the 2.0 version i want to do some more testing.
I've got this weekend off to and have a couple of hours on friday before the closed beta of D4 starts, so my goal is to be finish and release it on friday or at least this weekend :)

**Comment by Luffty** [comment] 2023-03-20 09:28
I wouldn't mind giving it a go before the official release, and see how it works out on my end (if you need it tested a little bit).
Truth to be told though, github is very unfamiliar to me, so finding the right things is a bit of a maze for me xD

And while i remember it, I've noticed the shitlist alarm have also been triggered while being nearby someone on the list, but without the ingame chat notification, as it's been while i wasn't grouped up.
Just figured I'd mention it as well :)

**Comment by Limmek** [comment] 2023-03-22 10:33
I was cleaning up the code and made some testing last night.
But i have some thoughts about the Announcement.
What do you think of removing the automatic announcements sent to x chat and add it to the drop-down list when you right click on a players frame instead (same place as add/remove player from shitlist) and here you select the desired chat to send the player reason and description in.

**Comment by Luffty** [comment] 2023-03-22 17:53
I think that personal choice of where to have it announced sounds like a splendid idea :-)
Maybe also a personal announcement other players can't see, whenever you get into the vicinity of a listed player (as that only plays the alarm in version 1.2, but doesn't announce it due to no party)

**Comment by Limmek** [comment] 2023-08-19 11:59
Sorry for the delay i did forgot about this...
Could you please try out this pre [release ](https://github.com/Limmek/Shitlist/releases/download/2.0.0/Shitlist-2.0.0.zip)for 2.0. Code still need improvements(hard coded translations) and cleanup but it should work out just fine.

#6 Fixed with this release

**Comment by Luffty** [comment] 2023-08-19 17:03
Initial implementation shows great promise, and functionality at first glance looks very promising :)
However, copy/pasting ontop of the original 1.1.2 leaves me with 1 minor issue:
Library with player and reason list is not fully read/imported (though with a full rewrite, something like this was expected).

https://imgur.com/a/e6XOPGE

**Comment by Luffty** [comment] 2023-08-19 18:21
Local error (33), as defined by bugsack - both with and without AngryAssignments loaded.

10x Shitlist/Shitlist.lua:71: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Shitlist/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...aceShitlist/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Shitlist/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Shitlist/Shitlist.lua"]:71: in function <Shitlist/Shitlist.lua:57>
[string "=[C]"]: ?
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"


 - - - - - - - -

10x Shitlist/Shitlist.lua:108: attempt to concatenate local 'realm' (a nil value)
[string "@Shitlist/Shitlist.lua"]:108: in function `GetOldConfigData'
[string "@Shitlist/Shitlist.lua"]:50: in function <Shitlist/Shitlist.lua:13>
[string "=[C]"]: ?
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@AngryAssignments/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 GetAuthor = <function> defined @Shitlist/ShitlistUtils.lua:12
 SetSound = <function> defined @Shitlist/ShitlistConfig.lua:715
 EnableModule = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @AngryAssignments/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 TimerFeedback = <function> defined @Shitlist/Shitlist.lua:328
 SecureHookScript = <function> defined @Shitlist/Libs/AceHook-3.0/AceHook-3.0.lua:409
 PrintDebug = <function> defined @Shitlist/ShitlistUtils.lua:43
 RawHookScript = <function> defined @Shitlist/Libs/AceHook-3.0/AceHook-3.0.lua:394
 GetReasonSelected = <function> defined @Shitlist/ShitlistConfig.lua:488
 Printf = <function> defined @AngryAssignments/libs/AceConsole-3.0/AceConsole-3.0.lua:65
 GetAlert = <function> defined @Shitlist/ShitlistConfig.lua:467
 SetDefaultModulePrototype = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SetListedPlayerAlert = <function> defined @Shitlist/ShitlistConfig.lua:703
 defaultModuleState = true
 IsEnabled = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @AngryAssignments/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetListedPlayerSelectedDescription = <function> defined @Shitlist/ShitlistConfig.lua:664
 RegisterMessage = <function> defined @AngryAssignments/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetArgs = <function> defined @AngryAssignments/libs/AceConsole-3.0/AceConsole-3.0.lua:140
 GetListedPlayerAlert = <function> defined @Shitlist/ShitlistConfig.lua:699
 IsHooked = <function> defined @Shitlist/Libs/AceHook-3.0/AceHook-3.0.lua:492
 baseName = "Shitlist"
 PlayAlert = <function> defined @Shitlist/ShitlistConfig.lua:720
 GetSound = <function> defined @Shitlist/ShitlistConfig.lua:711
 db = <table> {
 }
 Enable = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 SetListedPlayerSelected = <function> defined @Shitlist/ShitlistConfig.lua:585
 options = <table> {
 }
 SetEnabledState = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Shitlist/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 SetAlert = <function> defined @Shitlist/ShitlistConfig.lua:471
 RegisterEvent = <function> defined @AngryAssignments/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 SetListedPlayerSelectedDescription = <function> defined @Shitlist/ShitlistConfig.lua:668
 GameTooltip = <function> defined @Shitlist/Shitlist.lua:291
 SetDefaultModuleState = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 hooks = <table> {
 }
 IterateModules = <function> defined @AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 ToggleDebug = <function> defined @Shitlist/Shitlist.lua:377
 RawHook = <function> defined @Shitlist/Libs/AceHook-3.0/AceHook-3.0.lua:312
 GetReasonColor = <function> defined @Shitlist/ShitlistConfig.lua:539
 GetLicense = <function> defined @Shitlist/ShitlistUtils.lua:32
 SetListedPlayerName = <function> defined @Shitlist/ShitlistConfig.lua:622
 GetListedPlayerName = <function> defined @Shitlist/ShitlistConfig.lua:618
 S

**Comment by Limmek** [comment] 2023-08-21 08:23
Which version are you playing on Retail or Classic?

**Comment by Luffty** [comment] 2023-08-22 15:53
It also happens when I delete the Shitlist folder, and copy/paste a new from the zip file you provided.
I play classic wrath

**Comment by Luffty** [comment] 2023-08-23 16:31
This one pops up when I'm joining groups.
Using a clean addon folder of shitlist 2.0

5x [ADDON_ACTION_BLOCKED] AddOn 'Shitlist' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:226: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:179: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua"]:72: in function <...s/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:54>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Limmek** [comment] 2023-08-23 16:57
The [pre release](https://github.com/Limmek/Shitlist/releases/download/2.0.0/Shitlist-2.0.0.zip) is updated please try it now :)
Please remove the old Shitlist directory in Addons before adding the new pre release.
The first 2 issues mentioned [1685079015](https://github.com/Limmek/Shitlist/issues/5#issuecomment-1685079015) is fixed in this commit c572f63

**Comment by Luffty** [comment] 2023-08-24 20:14
So far, it works in mysterious ways ;)
Deleted old Shitlist folder in Addons.

No bugs reported, which is good.
Importing the old list (wherever it's located, documents folder?) looks like it works - but only for players listed with a server.
Players listed without a server in 1.1.2 have become a whole bunch of None-None in the newest 2.0.

During guild raid in ToTGC25 this evening, I also had 4 random guildies being added on shitlist, with a "None" reason applied to them, without me adding them

**Comment by Luffty** [comment] 2023-08-27 19:47
Using "Set Focus" on a player seems to set that player on shitlist with the "None" reason, just to add to the previous

**Comment by Luffty** [comment] 2023-09-03 19:03
Whispering and opening trade window with people also add them to shitlist, with a "None" reason

**Comment by Limmek** [comment] 2023-09-05 08:19
Thank you for taking time to test and for the feedback i will investigate it.

I will do some changes to how the old data is loaded.
Currently it checks for old listed players when the addon is loaded so i believe it will do this check on every loading screen. Also if the player name or realm is missing ( is blank) in the old listed player list it will not be added to the new list. That's why it did break in the first place and why some players where missing and/or not added at all. So that is why i did put a None to the name and realm variable if is was not found but apparently it did break other things.

So i think i will remove the feature where the addon is looking for the old listed players list and instead add a button in the settings menu that will only be shown if it finds any old data to be imported also some sort of popup-message that tells you if there is any old data found and if you want to migrate it.

All player data and reasons are saved in your wow [WTF folder](https://wowwiki-archive.fandom.com/wiki/Saving_variables_between_game_sessions#Storage) etc 
`WTF\Account\ACCOUNTNAME\SavedVariables\Shitlist.lua`

**Comment by Limmek** [comment] 2023-09-05 13:51
New [pre-release](https://github.com/Limmek/Shitlist/releases/download/2.0.0/Shitlist-2.0.0.zip)!

I did some changes and tests and i can not reproduce any of the mentioned issues now in the latest commit 2436e5d. Both retail and WotLK tested.
Button for import not yet implemented.
Keep in mind that when the old data is loaded from a version below 2.0 name or realm cant be blank/missing then it will not be merged to the new list. The reason why i want to store the listed players in a new list is to keep all variable names lowercase and the structure how the player data are stored is changed.

**Comment by Luffty** [comment] 2023-09-06 19:12
Deleted the old shitlist addon folder, and put the new pre-release in.
I also moved the shitlist.lua from the WTF folder, to check if it caused issues - no direct effect on current issues.
I still have problems with players being added to shitlist with a "None" reason, and I believe it relates to a general interact function.
They get added on whispers, on trades, on focus unit, on follow, on comparing achievements, and on inspects as well - I haven't checked on duels, but I'm 99% certain that one also prompts it

**Comment by Limmek** [comment] 2023-09-07 17:54
Please try the new [pre-release](https://github.com/Limmek/Shitlist/releases/download/2.0.0/Shitlist-2.0.0.zip).
Somehow i could reproduce it to after cleared wow cache so basically a fresh wotlk with only this addon.
**It is now resolved**! :) Keep in mind that when a new player is added the default reason is set to None. It's by design.

**Comment by Luffty** [comment] 2023-09-07 18:46
Nevermind the follow-up comment for now, my brain is apparently not yet awake - It did not register that I was looking at both my old comment and your new reply

**Comment by Luffty** [comment] 2023-09-07 19:34
Also, splendid with the resolve, I'm incapable of reproducing it myself now, however much I tried.
I'll look into the list import button in settings when It's included in a later release :)

**Comment by Luffty** [comment] 2023-09-10 21:22
Most recent bug catching as follows:

7x Shitlist/Shitlist.lua:290: Usage: UnitName("unit")
[string "=[C]"]: in function `UnitName'
[string "@Shitlist/Shitlist.lua"]:290: in function <Shitlist/Shitlist.lua:285>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
Skipped (In Encounter)

**Comment by Luffty** [comment] 2023-09-21 21:31
That latest bug, I figured out 1 way to force it by coincidence.
With original raid UI in wotlk, if i mouse over the target of a main tank, it will force the bug (if i'm not looking at the same target).
If i have also same enemy targetted, the bug will not appear.
It is unaffected by focus unit

**Comment by Limmek** [comment] 2023-09-22 06:16
Thanks for testing i will dig in to it this weekend

**Comment by Luffty** [comment] 2023-11-18 09:40
I dunno if you had any luck in your end on figuring out that unit name error, but I sure haven't.
It does occur at random times too though, which I'm not able to replicate - even when solo questing with a low lvl character, and out of the blue an error occurs

**Comment by Limmek** [comment] 2023-12-10 10:13
Sorry for the delay but the 2.0 version is finnaly released!🤣
Just waiting on curse to approve it and then it can be found in the curse client.

I will close this issue now and if you find any bug's in the new version please create a new 🐛bug report.

**Closed as completed by Limmek** 2023-12-10 10:13 UTC
Labels: Enhancement, In-progress
